import = [
  "~/.local/share/dotfiles/current/theme/alacritty.toml"
]

[window]
opacity = 0.8
padding.x = 8
padding.y = 10
decorations = "none"
dynamic_padding = false

[scrolling]
history = 10000

[font]
size = 12

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[cursor]
style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
]
