layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 1, match:namespace notifications
layerrule = blur on, match:namespace osd
layerrule = ignore_alpha 1, match:namespace osd
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0.41, match:namespace walker
