name = "ollama"
name_pretty = "Ollama"
fixed_order = true

[[entries]]
text = "Chat"
actions = { "chat" = "alacritty --class local.floating -e ollama-chat --chat" }

[[entries]]
text = "Select default model"
actions = { "select-default" = "alacritty --class local.floating -e ollama-chat --select" }

[[entries]]
text = "List models"
actions = { "list-models" = "alacritty --class local.floating -e ollama-chat --list" }

[[entries]]
text = "Pull model"
actions = { "pull-model" = "alacritty --class local.floating -e ollama-chat --pull" }

[[entries]]
text = "Remove model"
actions = { "remove-model" = "alacritty --class local.floating -e ollama-chat --rm" }

[[entries]]
text = "Install Ollama"
actions = { "install" = "alacritty --class local.floating -e ollama-chat --install" }
