name = "postgres"
name_pretty = "Postgres"
fixed_order = true
icon = ""

[[entries]]
icon = ""
text = "Setup postgres"
actions = { "postgres-setup" = "alacritty --class local.floating -e postgres-setup" }

[[entries]]
icon = ""
text = "Restore database"
actions = { "postgres-restore-db" = "alacritty --class local.floating -e postgres-restore-db" }

[[entries]]
icon = ""
text = "Backup database"
actions = { "postgres-backup" = "alacritty --class local.floating -e postgres-backup" }
