add_newline = true
command_timeout = 200
format = "[$directory$git_branch]($style)$character"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false

[git_branch]
style = "bold yellow"
symbol = ""
