input {
    kb_layout = us,ru,ua
    kb_variant =
    kb_model =
    kb_options = compose:caps, grp:alt_shift_toogle
    kb_rules =
    repeat_rate = 30
    repeat_delay = 350

    follow_mouse = 1

    sensitivity = 0
    touchpad {
        natural_scroll = false
    }
}
